name: Build and Deploy to Nuget

on:
  push:
    branches: [ main ]

env:
  NUGET_API_URL: https://api.nuget.org/v3/index.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Pack
        run: dotnet pack --no-dependencies -c Release
      - name: Find Package
        run: |
          mkdir -p ./packages
          find ** -type f -regex '.*\.s?nupkg' -exec mv {} ./packages/ \;
      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ./packages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: packages
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Push packages
        run: find ** -type f -iname '*.nupkg' -exec dotnet nuget push -s ${{ env.NUGET_API_URL }} -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate {} \;